# Generated by Django 5.2.4 on 2025-07-20 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='employerProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100, null=True)),
                ('aboutConpany', models.TextField(null=True)),
                ('conpanyLogo', models.ImageField(null=True, upload_to='static/img/logo')),
                ('location', models.TextField(null=True)),
                ('employerUser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='jobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('requirements', models.TextField(null=True)),
                ('salary', models.IntegerField(null=True)),
                ('jobType', models.CharField(choices=[('FullTime', 'Full Time'), ('Remote', 'Remote'), ('Internship', 'Internship')], max_length=100, null=True)),
                ('deadline', models.DateField(null=True)),
                ('postedDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('employer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='employer_app.employerprofilemodel')),
            ],
        ),
    ]
