# Generated by Django 5.2.4 on 2025-07-21 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer_app', '0002_alter_jobmodel_employer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='candidateProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100, null=True)),
                ('adress', models.TextField(null=True)),
                ('dateOfBirth', models.DateField(null=True)),
                ('candidateUser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='jobApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastEducation', models.CharField(max_length=20, null=True)),
                ('workExprience', models.TextField(null=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Interview', 'Interview'), ('Offered', 'Offered'), ('Rejected', 'Rejected')], max_length=100, null=True)),
                ('appliedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate_app.candidateprofilemodel')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employer_app.jobmodel')),
            ],
        ),
    ]
