# Generated by Django 5.2.4 on 2025-07-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0002_remove_jobapplicationmodel_lasteducation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofilemodel',
            name='lastEducation',
        ),
        migrations.RemoveField(
            model_name='candidateprofilemodel',
            name='workExprience',
        ),
        migrations.AddField(
            model_name='jobapplicationmodel',
            name='lastEducation',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobapplicationmodel',
            name='workExprience',
            field=models.TextField(null=True),
        ),
    ]
